name: On push to master

on:
  push:
    branches: [master]

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/do_lint.yml

  test:
    name: Test
    uses: ./.github/workflows/do_test.yml

  image:
    name: Create and publish a Docker image
    needs: [lint, test]
    uses: ./.github/workflows/do_build_image.yml
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
